fix: Leverage Puppeteer's native support for Firefox
smooth-code/jest-puppeteer pull request #356
Opened 2020-06-04 15:26 UTC by pyoor

## Summary

This PR is to address https://github.com/smooth-code/jest-puppeteer/issues/312.  Puppeteer now supports firefox natively.  As such, support for puppeteer-firefox is no longer required.  This PR replaces the `browser` property in `jest-puppeteer.config.js` in favor of the native `launch.product` key.

## Test plan
All existing tests pass and a new test was added to ensure that the `launch.product` value matches either `firefox` or `chrome`.

![image](https://user-images.githubusercontent.com/1735164/83776492-3d0ecd80-a656-11ea-8317-cd2569faec1b.png)

2020-08-11 22:25 UTC, Bialogs commented
I'm not sure this will work out of the box unless you also increase the puppeteer version in `package.json` to the version that supports Firefox .

2021-04-08 21:14 UTC, UziTech requested changes

2021-04-08 21:14 UTC, UziTech commented on packages/jest-environment-puppeteer/src/readConfig.js
> -      }
I think we need to keep the `getPuppeteer` function to allow using `puppeteer` or `puppeteer-core`

2021-04-16 05:35 UTC, UziTech approved these changes

2021-04-16 05:36 UTC, merged