Browser instance per Jest worker
smooth-code/jest-puppeteer pull request #420
Opened 2021-07-08 11:55 UTC by Nevenq

## Summary

Hello. I faced the problem described in [issue](https://github.com/smooth-code/jest-puppeteer/issues/409). 
 
In my case i cant run tests with multiple workers because the tests will affect to each other.  From different browsers i will be able to run tests from diffrent users.

I first implemented the feature system in my project. For example run tests with `--runInBand or -w 1`
![image](https://user-images.githubusercontent.com/38163651/124915726-4ca3d700-e00b-11eb-80c9-f7a0b197b844.png)

And workers count = 2 `-w 2`
![image](https://user-images.githubusercontent.com/38163651/124915875-76f59480-e00b-11eb-8e05-bd66f9e6d19e.png)

### Bug ?
If the number of workers is greater than the number of test cases in `setup.js`, more browser instances will be launched than will be used.
I tried to move the browser launch to `PuppeteerEnvironmet.js`, but there is no information about the launched browsers in` global.teardown` due to different contexts.

2021-07-08 15:15 UTC, Nevenq commented
P.S If run tests in `master` with `headless = false`. 
![image](https://user-images.githubusercontent.com/38163651/124946949-df06a380-e028-11eb-9a20-772b670fa8ba.png)

2021-07-11 23:38 UTC, UziTech commented
I think [jest project config](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig) does this already. You can specify different projects and each one will be run separately at once. I think if you separate your tests like this you can run each "project" in it's own browser.

2021-07-12 04:51 UTC, Nevenq commented
Do you think this is a good decision? I need to split my tests for one app into multiple projects? On what basis do I need to divide them then? So that the approximate time for passing tests for two projects is the same? What if I want to write more tests, I need to know and remember in which of the projects I need to write tests. It seems to me that there are too many dependencies and questions that jest itself can solve for us by distributing workers as the tests pass. Perhaps I'm wrong, but as a developer I would not like to monitor not only the correctness of tests, but also their distribution over "projects"

2021-07-12 05:33 UTC, UziTech commented
I see your point.

If the number of tests is less than the number of workers do the browsers just close without opening a page?

2021-07-12 05:45 UTC, Nevenq commented
No, they will be open until the global.teardown.js function is executed. I've tried moving the browser launch to PuppeteerEnvironment, but there are problems getting all the wsEndpoints. You can temporarily create a file with a list of all wsEndpoints and read this file in global.teardown.js. But it seems there were some problems with this solution.

2021-07-13 04:25 UTC, UziTech commented
Could we make this a setting so it would be backwards compatible for anyone who doesn't need it.

2021-07-13 04:44 UTC, Nevenq commented
Yes, `browserPerWorker:boolean` in `jest-puppeteer.config.js`.
`const browsersCount =
    config.browserPerWorker && !config.connect ? jestConfig.maxWorkers : 1`

2021-07-14 04:49 UTC, UziTech commented
Could you fix linting and tests?

2021-07-14 06:20 UTC, Nevenq commented
Today or tomorrow I will try to fix it

2021-07-21 21:24 UTC, UziTech requested changes

2021-07-21 21:24 UTC, UziTech commented on packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
> +    ]
Can we catch any parsing errors and throw a relevant error.

2021-07-21 21:24 UTC, UziTech commented on packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
> +const getWorkerIndex = () => process.env.JEST_WORKER_ID - FIRST_JEST_WORKER_ID
```suggestion
// JEST_WORKER_ID starts at 1
const getWorkerIndex = () => process.env.JEST_WORKER_ID - 1
```

2021-07-21 21:24 UTC, UziTech commented on packages/jest-environment-puppeteer/src/global.js
> +    config.browserPerWorker && !config.connect ? jestConfig.maxWorkers : 1
Need to document `browserPerWorker`

2021-07-28 05:24 UTC, UziTech requested changes

2021-07-28 05:24 UTC, UziTech commented on packages/jest-environment-puppeteer/src/global.js
> +  browsers.forEach((browser) => wsEndpoints.push(browser.wsEndpoint()))
```suggestion
  const wsEndpoints = browsers.map((browser) => browser.wsEndpoint())
```

2021-07-28 05:28 UTC, UziTech requested changes

2021-07-28 05:28 UTC, UziTech commented on packages/jest-environment-puppeteer/src/global.js
> +  )
```suggestion
  browsers = await Promise.all(
    Array.from({ length: browsersCount }).map(() =>
      openBrowser(puppeteer, config),
    ),
  )
```

2021-08-04 04:09 UTC, UziTech approved these changes

2021-09-23 03:40 UTC, merged